CREATE DATABASE MATRICULA;
USE MATRICULA;

CREATE TABLE ALUMNO(
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR(1) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR(80) UNIQUE NOT NULL,
NOMBRE_APODERADO VARCHAR(50) NOT NULL,
CELULAR_APODERADO CHAR(9) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(255) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO VARCHAR(50) NOT NULL
);

CREATE TABLE PAGOS(
ID_PAGO INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
MONTO DECIMAL(10,2) NOT NULL,
FECHA_PAGO DATETIME DEFAULT CURRENT_TIMESTAMP,
METODO VARCHAR(30) NOT NULL,
ESTADO VARCHAR(20) DEFAULT 'PAGADO',

FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO)
);

CREATE TABLE AULA(
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(40) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE CURSOS (
ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
CODIGO_CURSO CHAR(6) NOT NULL UNIQUE,
NOM_CURSO VARCHAR(40) NOT NULL,
CREDITO INT NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
ID_AULA INT,
FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);

CREATE TABLE RESERVA(
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE',
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);


CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(200) NOT NULL,
ESTADO TINYINT(1) DEFAULT 1
);




INSERT INTO AULA (NIVEL, GRADO, SECCION, VACANTES_TOTALES, VACANTES_DISPONIBLES)
VALUES
('SECUNDARIA', 3, 'A', 30, 5),
('SECUNDARIA', 3, 'B', 30, 0),
('PRIMARIA', 1, 'A', 25, 25),
('PRIMARIA', 6, 'B', 30, 12);


INSERT INTO USUARIO (USERNAME, PASSWORD_HASH)
VALUES ('ADMIN', '$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6');


INSERT INTO ALUMNO (
DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD,
GENERO, DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO,
CELULAR_APODERADO, USERNAME, PASSWORD_HASH, ESTADO
)
VALUES (
'45789865', 'Pepito', 'Rosales', '2004-05-15', 20, 'M',
'Av. Perú', '986532877', 'pepito@gmail.com', 'Sonia',
'986532789', 'Pepito', 'mundo', 'Activo'
);


INSERT INTO CURSOS (CODIGO_CURSO, NOM_CURSO, CREDITO, ESTADO, ID_AULA)
VALUES
('MAT001', 'Matemática', 4, 'Activo', 1),
('COM001', 'Comunicación', 3, 'Activo', 1),
('HIS001', 'Historia', 2, 'Activo', 2);
 
INSERT INTO PAGOS (ID_ALUMNO, MONTO, METODO, ESTADO)
VALUES
(1, 150.00, 'Efectivo', 'PAGADO'),
(1, 150.00, 'Yape', 'PENDIENTE');